<a href="https://colab.research.google.com/github/smart4ghari/Tensorflow/blob/master/00_tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow Fundamentals
* Introduction to Tensors
* Getting Information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using tf.function(a way to speed up regular python functions)
* Using GPU with tensorflow
* Exercises

## Introduction to Tensorflow

In [ ]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.5.0


In [ ]:
# Create tensor with tf.constant()
scalar = tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
# Let's check the dimension with ndim
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector
# Look at the below given information the shape changes and numpy also changes


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[1,2],
                     [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
matrix2 = tf.constant([[1.,2.],
                       [3.,4.],
                       [5.,6.]],dtype = tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [ ]:
# Number of dimensions of matrix2
matrix2.ndim

2

In [ ]:
# Now it's time to create tensor of our own
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                      [[13,14,15],
                       [16,17,19]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 19]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## What we've created so far
* Scalar - A single number
* Vector - A number with direction
* Matrix - A 2 dimensional array
* tensor - An n dimensional array

## Creating tensors with tf.Variable

In [ ]:
# Creating the above tensors with tf.Variable
changable_tensor = tf.Variable([10,3])
unchangable_tensor = tf.constant([10,10])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [ ]:
# Now inorder to change the values inside the list in changable_tensor use assign
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 3], dtype=int32)>

In [ ]:
# Let's try this for unchanable_tensor
unchangable_tensor[0].assign(11)
unchangable_tensor

AttributeError: ignored

## From the above two examples it is clear that tf.Variable() can be changed whereas tf.constant() cannot be changed

### Creating random tensors

In [ ]:
# Create two random(but the same) tensors
# from_seed allows us to create a same random numbers without changing
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape = (3,2))
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape = (3,2))
# Here normal stands for a bell shaped curve

random1,random2,random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## How to shuffle the order of elements in tensor?

In [ ]:
# This method is useful when we need to shuffle our data
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [5,6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)
# Whenever you run this cell again and again the 1st dimension items get shuffled
# Again and again and we don't want that so we're going to use set_seed method

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)
# And here we go the items didn't get shuffled when we write again and again

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) # Global level random seed
tf.random.shuffle(not_shuffled,seed = 42) # Operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

## Other way to make tensors

In [ ]:
## tensor ones
ones = tf.ones(shape = (3,4))
ones

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
## tensor zeros
zeros = tf.zeros(shape = (5,5))
zeros

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

# Turning Numpy arrays into tensors

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
# Now change the above numpy into tensor
tens_A = tf.constant(numpy_A)
tens_A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
tens_B = tf.constant(numpy_A,shape=(6,4))
tens_B

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]], dtype=int32)>

In [ ]:
tens_C = tf.constant(numpy_A,shape = (3,2,4))
tens_C

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# ✨✨ Getting information from our tensors
* Shape
* Rank
* Axis or Dimension
* Size

In [ ]:
# Create a rank 4 tensor (4 dimension tensor)
rank4_tensor = tf.zeros(shape = (2,3,4,5))
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank4_tensor.shape,rank4_tensor.ndim,tf.size(rank4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Getting various attributes of our tensor
print("Datatype of every element:",rank4_tensor.dtype)
print("Number of dimension(rank):",rank4_tensor.ndim)
print("Shape of tensor: ",rank4_tensor.shape)
print("Element along the 0th axis:",rank4_tensor.shape[0])
print("Element along the last axis:",rank4_tensor.shape[-1])
print("Total number of elements in our tensor:",tf.size(rank4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimension(rank): 4
Shape of tensor:  (2, 3, 4, 5)
Element along the 0th axis: 2
Element along the last axis: 5
Total number of elements in our tensor: 120


## Indexing Tensors
Tensors can be Indexed just like python lists

In [ ]:
# Get the first 2 elements of each dimension
rank4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except the final one
rank4_tensor[:1,:1,:1] # Leave the last one

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank4_tensor[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
rank4_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [ ]:
## Creating a rank2 tensor
rank2_tensor = tf.constant([[2,4],
                           [5,6]])
rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 6]], dtype=int32)>

In [ ]:
# Get the last item of each row
rank2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [ ]:
rank3_tensor = rank2_tensor[...,tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [4]],

       [[5],
        [6]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank2_tensor,axis = -1) # -1 means the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [4]],

       [[5],
        [6]]], dtype=int32)>

## Manipulating Tensors
**Basic Operations**
* Addition
* Subtraction
* Multiplication
* Division

In [ ]:
tensor = tf.constant([[10,22],
                      [98,9]])

In [ ]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 20,  32],
       [108,  19]], dtype=int32)>

In [ ]:
tensor
# Here the original tensor remains unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 22],
       [98,  9]], dtype=int32)>

## Like this we can use any operation

In [ ]:
# we can use the tensorflow built in functions too
tf.multiply(tensor,3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 30,  66],
       [294,  27]], dtype=int32)>

## Matrix Multiplication
In Machine learning matrix multiplication is one of the common topic

In [ ]:
# Matrix multiplicaton in TensorFlow
print(tensor)

tf.Tensor(
[[10 22]
 [98  9]], shape=(2, 2), dtype=int32)


In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2256,  418],
       [1862, 2237]], dtype=int32)>

In [ ]:
a = tf.constant([[1,2,5],
                  [7,2,1],
                  [3,3,3]])
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [ ]:
b = tf.constant([[3,5],
                 [6,7],
                 [1,8]])

In [ ]:
# Multiply a & b using matrix multiplication
c = tf.matmul(a,b)
print(c)

tf.Tensor(
[[20 59]
 [34 57]
 [30 60]], shape=(3, 2), dtype=int32)


In [ ]:
# Matrix Multiplication with python operator
a @ b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Try to multiply these two matrices of size (3,2)
a1 = tf.constant([[1,2],
                  [3,4],
                  [5,6]])
a1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
a2 = tf.constant([[7,8],
                  [9,10],
                  [11,12]])
a2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
# try to multiply two matrices of size (3,2) and (3,2)
a1 @ a2

InvalidArgumentError: ignored

In [ ]:
reshaped_a2 = tf.reshape(a2,shape = (2,3))

In [ ]:
a1 @ reshaped_a2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
a1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
a2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
transposed_a2 = tf.transpose(a2)

In [ ]:
transposed_a2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

# Always prefer to use transpose rather than reshape

# The Dot Product
* tf.matmul()
* tf.tensordot( )

In [ ]:
# perform the operation on x and y(Here any one of that should be transposed)
x = tf.constant([[1,2],
                 [8,7],
                 [3,1]])
y = tf.constant([[2,3],
                 [5,6],
                 [9,8]])

In [ ]:
tf.tensordot(tf.transpose(x),y,axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[69, 75],
       [48, 56]], dtype=int32)>

## Changing the datatype of the tensor

In [ ]:
# Let's create a tensor with default datatype(float32)
B = tf.constant([1.2,1.4])

In [ ]:
B.dtype

tf.float32

In [ ]:

C = tf.constant([1,2,3])

In [ ]:
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16
D = tf.cast(B,dtype = tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 1.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E = tf.cast(C,dtype = tf.float32)
E

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

## Aggregating Tensors
* Aggregation = Condensing them from multiple values to smaller amount of values

In [ ]:
tens1 = tf.constant([-9,-8])
tens1

In [ ]:
# To get the absolute value use abs method
tf.abs(tens1)

## Aggregation operations
* Minimum
* Maximum
* Mean
* Sum

In [ ]:
# Create a random tensor with values between 0 - 100 
rand_ten = tf.constant(np.random.randint(0,100,size = 50))
rand_ten

In [ ]:
# Find the minimum
tf.reduce_min(rand_ten)

In [ ]:
# Find the maximum
tf.reduce_max(rand_ten)

In [ ]:
# Find the mean
tf.reduce_mean(rand_ten)

In [ ]:
# Find the sum
tf.reduce_sum(rand_ten)

In [ ]:
# find the std deviation
tf.math.reduce_std(rand_ten,axis = 0)

# For Variance and Standard deviation we can't able to find like the previous one so let's move onto tensorflow probability

In [ ]:
import tensorflow_probability as tfp

In [ ]:
tfp.stats.stddev(tf.cast(rand_ten,dtype = tf.float32))

In [ ]:
tfp.stats.variance(rand_ten)

## Find the positonal maximum and minimum

In [ ]:
# Create a new tensor for finding positional min and max
tf.random.set_seed(2)
F = tf.random.uniform(shape= [50])
F

In [ ]:
# Find the postional maximum
## Here the positional maximum just gives the position which is index
tf.argmax(F)

In [ ]:
# Index of the positional maximum
F[tf.argmax(F)]

In [ ]:
# Find the max val of F
tf.reduce_max(F)

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

In [ ]:
# Find the positional minimum (Index)
tf.argmin(F)

In [ ]:
# Find the value of the index 
F[tf.argmin(F)]

## Squeezing a tensor(Removing one dimension)

In [ ]:
tf.random.set_seed(2)
tens2 = tf.constant(tf.random.uniform(shape=(1,1,1,50)))
tens2

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.14690244, 0.46425676, 0.22489977, 0.35288846, 0.9857408 ,
          0.99910235, 0.5648881 , 0.16375077, 0.9890269 , 0.681414  ,
          0.9361813 , 0.76035094, 0.8557707 , 0.42701852, 0.3893944 ,
          0.69739926, 0.6512991 , 0.08290601, 0.3726778 , 0.06093955,
          0.96939087, 0.09901857, 0.40164733, 0.1655829 , 0.8469081 ,
          0.64433956, 0.90287995, 0.7110901 , 0.6869948 , 0.6519774 ,
          0.09213817, 0.8334286 , 0.440794  , 0.67382956, 0.29321003,
          0.7938975 , 0.69646835, 0.3866577 , 0.79191923, 0.23676014,
          0.9113256 , 0.73570395, 0.40668976, 0.9452349 , 0.10045171,
          0.9370924 , 0.86061335, 0.37275386, 0.8774456 , 0.8208276 ]]]],
      dtype=float32)>

In [ ]:
# Squeezing the tensor
squeezed_tensor = tf.squeeze(tens2)
squeezed_tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.14690244, 0.46425676, 0.22489977, 0.35288846, 0.9857408 ,
       0.99910235, 0.5648881 , 0.16375077, 0.9890269 , 0.681414  ,
       0.9361813 , 0.76035094, 0.8557707 , 0.42701852, 0.3893944 ,
       0.69739926, 0.6512991 , 0.08290601, 0.3726778 , 0.06093955,
       0.96939087, 0.09901857, 0.40164733, 0.1655829 , 0.8469081 ,
       0.64433956, 0.90287995, 0.7110901 , 0.6869948 , 0.6519774 ,
       0.09213817, 0.8334286 , 0.440794  , 0.67382956, 0.29321003,
       0.7938975 , 0.69646835, 0.3866577 , 0.79191923, 0.23676014,
       0.9113256 , 0.73570395, 0.40668976, 0.9452349 , 0.10045171,
       0.9370924 , 0.86061335, 0.37275386, 0.8774456 , 0.8208276 ],
      dtype=float32)>

# One hot encoding tensors

In [ ]:
some_list = [0,1,2,3] 
# Could be anything for ex let's assume 0-red,1-green,2-blue,3-yellow

# while doing one_hot we'll always need to define the depth
depth = 4
tf.one_hot(some_list,depth) 

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding "True","False" for on_values,off_values
tf.one_hot(some_list,depth,on_value = "True",off_value = "False")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'True', b'False', b'False', b'False'],
       [b'False', b'True', b'False', b'False'],
       [b'False', b'False', b'True', b'False'],
       [b'False', b'False', b'False', b'True']], dtype=object)>

## Squaring,log,Square root 

In [ ]:
# Creating a tensor in a new way
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Squaring the tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Taking log
tf.math.log(tf.cast(H,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
# Find the squareroot
tf.sqrt(tf.cast(H,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

## Tensors and NumPy

In [ ]:
# Create a tensor using Numpy
J = tf.constant(np.array([3,2,1,10]))
J

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 3,  2,  1, 10])>

In [ ]:
# Convert our tensor back to numpy array
np.array(J), type(np.array(J))

(array([ 3,  2,  1, 10]), numpy.ndarray)

In [ ]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([1,2,3]))
tensor_J = tf.constant([1,2,3])
numpy_J.dtype, tensor_J.dtype

(tf.int64, tf.int32)

## Finding access to GPU

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]