In [1]:
import numpy as np

In [4]:
np.random.seed(0)
rand1 = np.random.randint(10,size = (5,3))
rand2 = np.random.randint(10,size = (5,3))

In [5]:
rand1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [6]:
rand2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

## Element wise multiplication (or) Ordinary Multiplication

In [7]:
rand1 * rand2 
# Here we'll get the output because it's a element wise multiplication

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

# Dot procuct

In [9]:
np.dot(rand1,rand2)
# Here we'll get an error because dot product multiplication is known as
# Matrix Multiplication here the shape of our matrices are (5,3) and (5,3)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [11]:
# 5x3 5x3 matrix multiplication isn't possible
# So we need to reshape the array 5x3 3x5 we don't get an error now
rand1_reshape = rand1.reshape((3,5))

In [12]:
rand1_reshape

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [14]:
# Now multiply
np.dot(rand1_reshape,rand2)

array([[ 90, 103,  62],
       [143, 132, 123],
       [197, 148, 151]])