## Manipulating and Comparing Arrays

## Here we'll perform some basic arithmetic operations 😊

In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])

In [5]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

# Addition ✨

In [7]:
sum1 = a1 + a2

In [8]:
print(sum1)

[[2 4 6]
 [5 7 9]]


In [9]:
sum2 = np.add(a1,a2)

In [10]:
print(sum2)

[[2 4 6]
 [5 7 9]]


# Subtraction 🐱‍🏍🐱‍🏍

In [11]:
sub1 = a1 - a2

In [12]:
print(sub1)

[[ 0  0  0]
 [-3 -3 -3]]


In [13]:
sub2 = np.subtract(a1,a2)

In [14]:
print(sub2)

[[ 0  0  0]
 [-3 -3 -3]]


In [15]:
sub3 = a1 - a3

In [16]:
print(sub3)

[[[  0   0   0]
  [ -3  -3  -3]
  [ -6  -6  -6]]

 [[ -9  -9  -9]
  [-12 -12 -12]
  [-15 -15 -15]]]


# Multiplication 💕

In [18]:
mul1 = a1 * a2

In [19]:
print(mul1)

[[ 1  4  9]
 [ 4 10 18]]


In [20]:
mul2 = np.multiply(a1,a2)

In [21]:
print(mul2)

[[ 1  4  9]
 [ 4 10 18]]


In [22]:
mul3 = np.multiply(a1,a3)

In [23]:
print(mul3)

[[[ 1  4  9]
  [ 4 10 18]
  [ 7 16 27]]

 [[10 22 36]
  [13 28 45]
  [16 34 54]]]


# Division 🐱‍💻

In [24]:
div1 = a1 // a2 # Floor division won't give any decimal points

In [25]:
print(div1)

[[1 1 1]
 [0 0 0]]


In [26]:
div2 = a1 / a2

In [27]:
print(div2)

[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]


In [28]:
div3 = np.divide(a1,a2)

In [29]:
print(div3)

[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]


# Modulo ✌️

In [30]:
mod1 = np.mod(a1,a3)

In [31]:
print(mod1)

[[[0 0 0]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [32]:
mod2 = a1 % a3

In [33]:
print(mod2)

[[[0 0 0]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]


# Logarthimic 🎁

In [37]:
log1 = np.log(a1)

In [38]:
print(log1)

[0.         0.69314718 1.09861229]


# Exponent 🥇

In [39]:
exp1 = np.exp(a3)

In [40]:
print(exp1)

[[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
  [5.45981500e+01 1.48413159e+02 4.03428793e+02]
  [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

 [[2.20264658e+04 5.98741417e+04 1.62754791e+05]
  [4.42413392e+05 1.20260428e+06 3.26901737e+06]
  [8.88611052e+06 2.41549528e+07 6.56599691e+07]]]
