In [1]:
import numpy as np

## Datatype & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3.3],
              [2.2,4,5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
                 [[10,11,21],
                 [13,14,15],
                 [16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [2.2, 4. , 5. ]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 21],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a3.shape    

# The output will be in the form of
# ('row','col','dimensions')

(2, 3, 3)

In [11]:
print(f"The dimension of a1: {a1.ndim}\nThe dimension of a2: {a2.ndim}\nThe dimension of a3: {a3.ndim}")

The dimension of a1: 1
The dimension of a2: 2
The dimension of a3: 3


In [13]:
# To print the datatype
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
# To print the size
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Using other libraries with numpy a simple example

In [19]:
import pandas as pd

df = pd.DataFrame(a2)

df

0    1    2
0  1.0  2.0  3.3
1  2.2  4.0  5.0

# Creating arrays using numpy

In [28]:
# Creating ones using numpy
ones = np.ones((3,3))

# ones = np.ones((3,3),dtype = "int32")

### Default dtype is None if you want to change it you can

In [29]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
print(ones.dtype)

float64


In [31]:
type(ones)

numpy.ndarray

In [32]:
zeros = np.zeros((2,3))

In [33]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
zeros.dtype

dtype('float64')

In [35]:
type(zeros)

numpy.ndarray

# arange function in numpy

In [36]:
range_array = np.arange(0,10)

In [38]:
print(range_array)

[0 1 2 3 4 5 6 7 8 9]


# random function in numpy

In [39]:
random_array = np.random.randint(0, 10, size = (4,4))

In [40]:
print(random_array)

[[6 8 0 4]
 [4 9 0 7]
 [9 9 0 4]
 [3 5 0 7]]


In [41]:
random_array.size

16

In [42]:
random_array.shape

(4, 4)

In [43]:
random_array1 = np.random.random((4,4))
print(random_array1)

[[0.76151779 0.56110754 0.29870721 0.92976187]
 [0.4988632  0.77702926 0.55370015 0.36255413]
 [0.50351524 0.93476854 0.27844216 0.45745907]
 [0.0322973  0.49801298 0.83706497 0.27289076]]


In [45]:
# rand also does the same job like random
random_array2 = np.random.rand(4,4)
print(random_array2)

[[0.26399856 0.98196535 0.46192812 0.05995667]
 [0.9850453  0.7356663  0.16185532 0.47031097]
 [0.86843987 0.32202574 0.67525732 0.12876954]
 [0.43043776 0.50849261 0.58439446 0.36934709]]
