In [1]:
list_2 = [x**2 for x in range(1,4)]
print(list_2)

[1, 4, 9]


In [2]:
list_3 = [x**3 for x in range(1,4)]
print(list_3)

[1, 8, 27]


In [3]:
list_sum = [list_2[i] + list_3[i] for i in range(len(list_2))]

In [4]:
list_sum

[2, 12, 36]

## We'll implement the above same code using Numpy

In [5]:
import numpy as np

In [6]:
arr_2 = np.arange(1,4) # Very similar to range but it creates an array

In [7]:
print(arr_2)

[1 2 3]


In [17]:
# For getting the power 2 
arr_2 = np.arange(1,4) ** 2
arr_3 = np.arange(1,4) ** 3
print(arr_2 + arr_3)

[ 2 12 36]


In [23]:
sample = np.array([1,2,3,4])

In [20]:
print(np.power(sample,3))

[ 1  8 27 64]


In [26]:
print(np.exp(sample))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [27]:
print(np.log(sample))

[0.         0.69314718 1.09861229 1.38629436]


In [28]:
print(np.sin(sample))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
