## Reshaping and Transposing

In [1]:
import numpy as np

In [2]:
a2 = np.array([[1,2,3.3],
              [2.2,4,5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
                 [[10,11,21],
                 [13,14,15],
                 [16,17,18]]])

In [3]:
# Due to numpy broadcasting error will occur
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

# So we need to reshape

In [4]:
a2_reshape = a2.reshape((2,3,1)) # Any argument value should be 1

In [5]:
print(a2_reshape)

[[[1. ]
  [2. ]
  [3.3]]

 [[2.2]
  [4. ]
  [5. ]]]


In [7]:
a2_reshape * a3

array([[[ 1. ,  2. ,  3. ],
        [ 8. , 10. , 12. ],
        [23.1, 26.4, 29.7]],

       [[22. , 24.2, 46.2],
        [52. , 56. , 60. ],
        [80. , 85. , 90. ]]])

# Transpose

In [13]:
a2_T = a2.T

In [14]:
a3_T = a3.T

In [15]:
a2_T

array([[1. , 2.2],
       [2. , 4. ],
       [3.3, 5. ]])

In [16]:
a3_T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 21],
        [ 6, 15],
        [ 9, 18]]])

In [17]:
a2_T.shape

(3, 2)

In [18]:
a3_T.shape

(3, 3, 2)