## Vieweing Arrays and Matrices

## Unique function

In [1]:
import numpy as np

In [2]:
random_arr = np.random.randint(10,size = (5,4))
print(random_arr)

[[9 4 7 7]
 [9 9 0 4]
 [4 3 4 1]
 [4 6 2 2]
 [0 5 7 6]]


In [5]:
unique = np.unique(random_arr)
print(unique)

[0 1 2 3 4 5 6 7 9]


In [9]:
a1 = np.array([12,12,14])

In [10]:
a2 = np.array([[1,2,3],
              [4,5,6]])

In [11]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [12]:
a1

array([12, 12, 14])

In [13]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
a1[1]

12

In [16]:
a2[1]

array([4, 5, 6])

In [17]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [20]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [23]:
a4 = np.random.randint(10,size = (2,3,4,5)) # 4d array
# Practice to count from the outermost number it'll be the best

In [24]:
print(a4)

[[[[9 6 4 9 7]
   [2 6 5 2 7]
   [0 6 1 7 6]
   [0 5 6 2 8]]

  [[6 2 0 7 7]
   [7 7 4 7 6]
   [0 6 8 5 8]
   [2 8 1 7 4]]

  [[2 4 2 5 7]
   [1 2 3 4 8]
   [4 0 5 9 2]
   [0 9 0 1 2]]]


 [[[0 2 1 3 1]
   [4 1 0 8 2]
   [0 8 0 4 6]
   [9 2 0 9 6]]

  [[9 9 9 7 4]
   [0 6 8 3 5]
   [6 9 4 4 0]
   [2 8 3 3 5]]

  [[2 6 5 8 3]
   [5 4 0 9 4]
   [7 5 5 1 6]
   [7 3 7 4 5]]]]


In [33]:
 a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [34]:
# Get the first 4 numbers of innermost array
a4[:,:,:,:4]

array([[[[9, 6, 4, 9],
         [2, 6, 5, 2],
         [0, 6, 1, 7],
         [0, 5, 6, 2]],

        [[6, 2, 0, 7],
         [7, 7, 4, 7],
         [0, 6, 8, 5],
         [2, 8, 1, 7]],

        [[2, 4, 2, 5],
         [1, 2, 3, 4],
         [4, 0, 5, 9],
         [0, 9, 0, 1]]],


       [[[0, 2, 1, 3],
         [4, 1, 0, 8],
         [0, 8, 0, 4],
         [9, 2, 0, 9]],

        [[9, 9, 9, 7],
         [0, 6, 8, 3],
         [6, 9, 4, 4],
         [2, 8, 3, 3]],

        [[2, 6, 5, 8],
         [5, 4, 0, 9],
         [7, 5, 5, 1],
         [7, 3, 7, 4]]]])

In [36]:
a4[:,:,:,:2]

array([[[[9, 6],
         [2, 6],
         [0, 6],
         [0, 5]],

        [[6, 2],
         [7, 7],
         [0, 6],
         [2, 8]],

        [[2, 4],
         [1, 2],
         [4, 0],
         [0, 9]]],


       [[[0, 2],
         [4, 1],
         [0, 8],
         [9, 2]],

        [[9, 9],
         [0, 6],
         [6, 9],
         [2, 8]],

        [[2, 6],
         [5, 4],
         [7, 5],
         [7, 3]]]])